name: driver_portal
description: A Driver Portal Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  permission_handler: ^12.0.1
  redis_dart: 0.1.0+4
  logging: ^1.1.1
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.0
  geolocator: ^14.0.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^6.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  http: ^1.2.2
  url_launcher: ^6.1.11
  image_picker: ^1.2.0
  table_calendar: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true