version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: margdarshak-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  redis-data:
  mongo-data:
